### ISSUE TITLE
First contract analysis: safeMath and gas optimizations

### ISSUE THREAD

**Issue by miguelmtzinf** [stocksdapp/contracts#1]
At first glance, contracts codebase seems fine overall. Here some thoughts:
- There are some requires that restricts access to functions based on SToken and SExchange ownership. It would be great to add Onwable pattern or just a modifier to save some gas units.
- SafeMath is being used for uint256 operations, but int256 operations are not safe. [SignedSafeMath](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/math/SignedSafeMath.sol) could solve this issue.
- There is a constant called BURN_RATE, which is used for creating dividends. It would be great to rename it.
- The SExchange works with DAI stablecoin and funcionality of SExchange and DAI transfers are coupled, so that's blocks the incorporation of more stablecoins to the system.
- We should keep in mind that the protocol may change in the future, so we need to discuss some upgradeability mechanisms or just take care of the contracts design in order to know which parts are susceptible to change (STOCKSD token should lasts).

In my opinion, we should find a golden balance between simple and secure contracts in order to release the system asap. I would leave the contracts as is, with no more features, but fixing and enhancing those parts which affects the security.

**Comment by stocksd** [comment]
@miguelmartinezinf 

Linked to your PR.

I think you addressed first three points in your PR effectively, I have some thoughts about last two though (adding more stablecoins and upgradeability). 

As I think you already guessed SExchange (we should probably rename that too before release :) ) used DAI interface to withdraw dividends in DAI (in addition to dividends in STOCKSD). We will most certainly be expanding stablecoins in exchange contract and hence we shouldn't actually keep this DAI hard reference in token contract which IMO should be non-upgradeable.

I see two solutions: either extract this part into a separate upgradeable contract referenced by token contract, or ditch DAI dividends altogether. I'm inclining towards the latter (it's basically a nice perk but comes with too many headaches).

I think we should probably have a quick discussion on tokenomics, but I think dividend token is already a good value proposition.
